export const CAMPAIGN_LIST_REQUEST = 'CAMPAIGN_LIST_REQUEST';
export const CAMPAIGN_LIST_SUCCESS = 'CAMPAIGN_LIST_SUCCESS';

export const CAMPAIGN_NAME_CHANGED = 'CAMPAIGN_NAME_CHANGED';
export const CREATE_NEW_CAMPAIGN = 'CREATE_NEW_CAMPAIGN';
